### ISSUE TITLE
Text only Tiles display content side on initial load

### ISSUE THREAD

**Issue by siddhi-gh** [tejas-k3/tejas-kothari-portfolio#10]
### Issue
- The Tiles that only have text in `tileName` and `content`, display the `content` side on the initial load of website.

<img width="1440" alt="Screenshot 2023-06-07 at 11 39 52 PM" src="https://github.com/tejas-k3/tejas-kothari-portfolio/assets/91131867/34ece07d-a43e-4922-bbc8-acf63a5e3801">

### Expected Behaviour
- Text only tiles should always have the `tileName` side up on the initial load of website.
- Tiles with `icon` should always have the `icon` side up on the initial load of website.

**Comment by aswin2108** [comment]
I would like to try this!

**Comment by siddhi-gh** [comment]
> I would like to try this!

Few points to note that may prove useful while fixing this issue:

- The `json` object for tiles data is not consistent
<img width="1440" alt="Screenshot 2023-06-10 at 4 44 26 PM" src="https://github.com/tejas-k3/tejas-kothari-portfolio/assets/91131867/c1d42f71-3f37-4094-9f80-0e91b398e027">

- Tiles that only have text on either side have a `string` in `content` prop:
```
{
      "tileName": "Who am I?",
      "content": "Software Enginner coding for passion & engineering",
      "isSquare": true,
      "color": "#00539CFF"
},
```

- Tiles that have `icon` on one side have an `icon` object in `content` prop:
```
{
      "tileName": "My Github",
      "content": {
        "type": "iconLink",
        "url": "https://github.com/tejas-k3",
        "iconSrc": "https://pic.onlinewebfonts.com/svg/img_258190.png",
        "iconAlt": "Icon"
      },
      "isSquare": false,
      "color": "#4183C4"
},
```

- You will notice here that the `icon` object is being passed to the `content` prop instead of `tileName` prop. 
- Since we intend to show the `tileName` side up on the initial load, we should be passing the `icon` object to `tileName`, instead of passing it to `content`.
- And after the `json` object is fixed, you may want to verify the flipped state of tiles in `Tile.js` file.

**Comment by tejas-k3** [comment]
Code is written in specific way to support this type of content split where 
```
"content": {
        "type": "iconLink",
``` refers to a hyperlink with image
` "content": "Software Enginner coding for passion & engineering",` refers to string content

**Comment by siddhi-gh** [comment]
That's given, and it is what's causing this issue of text only `Tiles` to have content side up on the first load instead of the `tileName`.

The goal here is to find a solution to be able to have the `tileName` side up in case of text only `tiles` and `icon` side up in case of `tiles` with `icon`.
