### ISSUE TITLE
Tile animation is not available in v2

### ISSUE THREAD

**Issue by tejas-k3** [tejas-k3/tejas-kothari-portfolio#12]
The flipping animation is not working in v2

v1 View :

https://github.com/tejas-k3/tejas-kothari-portfolio/assets/77725958/9b42d642-ca9a-42c6-8345-5f72080553ca

v2 View :
https://github.com/tejas-k3/tejas-kothari-portfolio/assets/77725958/08f10f40-a5be-4390-b2ce-c6c8e3fbecc9

**Comment by siddhi-gh** [comment]
This was fixed in:
- #11 

@tejas-k3 You can verify the same and close this issue.
