### ISSUE TITLE
Removal of warning

### ISSUE THREAD

**Issue by tejas-k3** [tejas-k3/tejas-kothari-portfolio#13]
Current run shows following warnings which should be addressed without impacting functionalities
`TEJAS@Tejas-iPotato MINGW64 /d/tejas-kothari-portfolio (fix-tile-transition)
$ npm start

> tejas-kothari-portfolio@0.1.0 start
> react-scripts start

(node:12676) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Starting the development server...

Compiled with warnings.

./src/utils/getColorHue.js
  Line 15:  Expected a default case  default-case

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
`

**Comment by siddhi-gh** [comment]
> Current run shows following warnings which should be addressed without impacting functionalities `TEJAS@Tejas-iPotato MINGW64 /d/tejas-kothari-portfolio (fix-tile-transition) $ npm start
> 
> > tejas-kothari-portfolio@0.1.0 start
> > react-scripts start
> 
> (node:12676) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated. (Use `node --trace-deprecation ...` to show where the warning was created) Starting the development server...
> 
> Compiled with warnings.
> 
> ./src/utils/getColorHue.js Line 15: Expected a default case default-case
> 
> Search for the keywords to learn more about each warning. To ignore, add // eslint-disable-next-line to the line before. `

- I pushed a fix for this console warning in PR #11 

  - `getColorHue` util function was missing a `default` case in the `switch` statement to fallback on when there are unmatched cases.

- If the `default` case is executed, `hue` is set to 0.
