### ISSUE TITLE
Hyperlinks do not open the second time

### ISSUE THREAD

**Issue by siddhi-gh** [tejas-k3/tejas-kothari-portfolio#17]
### Issue
- The `tiles` that have hyperlink (examples - Linkedin, GitHub) do not open the external link when they are clicked second time.

https://github.com/tejas-k3/tejas-kothari-portfolio/assets/91131867/da748820-de6b-41b9-93b8-0240ffde4e4d

### Steps to Reproduce
- In the Portfolio website click on a `tile` that includes hyperlink and try successive clicks.
- Notice that the external website opens the first time the `tile` is clicked but it does not work on subsequent clicks.

### Expected Behaviour
- Tiles that have hyperlink should always open the associated website.

**Comment by aswin2108** [comment]
![image](https://github.com/tejas-k3/tejas-kothari-portfolio/assets/72661784/6518e0be-482c-45cd-98fe-f284df68e1bf)

Here, we are not using hook the right way! There are two ways to fix it:
* Either remove the `if` statement in the hook and replace the 66th line to just complement the value.
* The second way is to remove the hook and make it as a function and just call it inside the `renderContent()`
Which one to proceed with?

**Comment by siddhi-gh** [comment]
That's a good catch!

I would like it if we were able to remove the "useEffect" hook and create a
function instead.

**Comment by aswin2108** [comment]
Actually I found a mistake in what I typed thats why I deleted it! On doubt I have is that do we need to open the link when the icon card is clicked? Like for github do we need to open the site when it has the icon and also when its in the flipped state (when it shows "My Github")?

**Comment by siddhi-gh** [comment]
As per my understanding, No. We should redirect only when the icon is clicked. 
Perhaps the project owner would be the right person to comment on this.

**Comment by tejas-k3** [comment]
@aswin2108 The expected behaviour is 
- Title should be visible on first load and not the icons.
- Clicking on icon should open respective link in new window.

@siddhi-gh can comment on final approach, as long as the desired functionality is achieved without breaking existing code, I'm good with it.

**Comment by aswin2108** [comment]
@tejas-k3 So, for the first load the tileName should be shown instead of the icons? Isnt the current way better?

**Comment by siddhi-gh** [comment]
@aswin2108 If you'd like to try and test something out to fix this issue please proceed, else I have a one liner fix for the same.

**Comment by tejas-k3** [comment]
@aswin2108 As per my understanding and presumption, text prompts user to click on it which triggers animation enhancing experience and it is a better flow as we're triggering flip animation on icon click too.

If Icons are visible on first load
- User clicks on icon and gets navigated to new window. (Flip animation gets missed)
- User closes new window and now the original tile is having text.

If Icons aren't visible on first load.
- User clicks on text.
- Icons are visible now with good transition.

**Comment by siddhi-gh** [comment]
I like the look and feel of the website as it is currently. 
- The flip is still available for icon tiles. You click on the icon:
  - tile flips -> shows text.
  - the link is opened in a new tab after a delay of 5s.

- If you want, we can prompt the icon tiles to flip back to the icon side after the external link is opened in a new tab.

**Comment by tejas-k3** [comment]
@aswin2108 Let's lock in on keeping the current way then.
CC : @siddhi-gh

**Comment by aswin2108** [comment]
@tejas-k3 Yeah not only that, the current version looks a bit non-uniform as there are some text tiles and some icon tiles which makes it a better way to look at! The other thing is that this current version actually reduces the number of clicks to open up the pages!

**Comment by aswin2108** [comment]
@tejas-k3 So icon clicks or tile clicks???

**Comment by tejas-k3** [comment]
@aswin2108 Icons approach only
