### ISSUE TITLE
Project start & build doesnt work with same command on diff platforms

### ISSUE THREAD

**Issue by tejas-k3** [tejas-k3/tejas-kothari-portfolio#8]
The project requires changes in package.json for following scripts ->
For Mac platform :-
    "start": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-scripts start",
    "build": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-scripts build",

For Windows platform :-
    "start": "react-scripts start",
    "build": "react-scripts build",

**Comment by siddhi-gh** [comment]
Created a PR to fix this issue:
- #15 

- fixed it by Installing `cross-env` as a dev dependency which is a solution that allows to set environment variables in a cross-platform manner.

**Comment by tejas-k3** [comment]
Done & merged as part of #15
