### ISSUE TITLE
Redirect hyperlinks to new Tab

### ISSUE THREAD

**Issue by ghsiddhi** [tejas-k3/tejas-kothari-portfolio#9]
### Issue
- The tiles that have external link associated (examples - Linkedin, GitHub) opens the website in the same tab.

### Steps to Reproduce
- In the Portfolio website click on a tile that includes hyperlink.
- Notice that the external website opens in the same tab.

### Expected Behaviour
- External links should be opened in a new tab.

**Comment by tejas-k3** [comment]
Fixed as part of #14

**Comment by siddhi-gh** [comment]
We should make it a practice to close down an issue only after the corresponding PR raised to fix it is merged after proper testing.
